### ISSUE TITLE
Res Bldg-SFD- "Open or Closed Driveway" no options.

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1176]
There are no options to select in the drop down bar for "Open or Closed Driveway?"-AW
![image](https://user-images.githubusercontent.com/47611580/59618606-92289b00-90f6-11e9-9f2e-5dc5afc24700.png)

**Comment by calequin** [comment]
working on this with @megisys

**Comment by calequin** [comment]
Rhythm only supports enumerations or code definitions in our drop downs, you cannot use manual list items. Need to work this out with @megisys

**Comment by calequin** [comment]
changed the old dropdown to only visible for hansen 7 migrated data and added new popup box for ips 11.
added DrivewayOpenClose code definition table in schema manager. fixed workflow formulas that contained dwoc and changed them to DrivewayOpenClose.Code

Fixed in Test

**Comment by ABonomo21** [comment]
drop down still does not work on sfd

![image](https://user-images.githubusercontent.com/47611580/60046461-60cf4280-9695-11e9-8dcc-e7a4b739f645.png)

**Comment by calequin** [comment]
fixed by regenerating detail page from preprod
![image](https://user-images.githubusercontent.com/47603568/60101615-15b33f00-972a-11e9-8abc-d32fbabf5e3e.png)

**Comment by ABonomo21** [comment]
not working on Zoning Certificate-AW
![image](https://user-images.githubusercontent.com/47611580/60108206-3e413600-9736-11e9-9b7f-d9b4f8489420.png)
