### ISSUE TITLE
PLANNING - PLAT - work type ALL PLATS

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1916]
After 1st round of reviews an additional fee (PRE-FINAL PLAT PLANNING FEE $1,182) populated that is incorrect and not related to this work type. I do not understand why this would have populated, especially since we have already tested and signed off on these fees. 
Looking to find out why this fee populated, or when it was changed 
Ultimately, the fee need to be removed because it is incorrect.
AREED

![image](https://user-images.githubusercontent.com/4129185/65712502-3199ea00-e065-11e9-9bfc-fab32e32f569.png)
![image](https://user-images.githubusercontent.com/4129185/65712540-424a6000-e065-11e9-8fa1-81b18297271a.png)

**Comment by dhenry-KCI** [comment]
Also happening on ADDITION PLAT PL245444 - This seems wide spread under PLAT

**Comment by dhenry-KCI** [comment]
This fee is adding on every resubmission
![image](https://user-images.githubusercontent.com/4129185/65713357-057f6880-e067-11e9-808f-9393abe61d33.png)

**Comment by calequin** [comment]
Fixed. formula had a mispelling

**Comment by dhenry-KCI** [comment]
This is not corrected and it does not make sense why this happened. This is the same issue we asked to be explained to us previously. Why is this occurring? @megisys @dhenry-KCI 
Please see multiple explanations below that do not appear to be correct since it is still happening. AR

![image](https://user-images.githubusercontent.com/4129185/66506272-07035480-ea9b-11e9-942b-043f4ed59c42.png)
![image](https://user-images.githubusercontent.com/4129185/66506560-91e44f00-ea9b-11e9-89f0-72105b2328ad.png)
![image](https://user-images.githubusercontent.com/4129185/66506678-cc4dec00-ea9b-11e9-9c8e-e14ae713a25c.png)

**Comment by megisys** [comment]
I believe the formula was corrupted. I created a brand new version and it is no longer happening
