### ISSUE TITLE
City Impact - Fee Error

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#690]
Incorrect fees populated for RESSFD, the additional fees added, should be City Detached for ES, MS, HS and City Library 
![image](https://user-images.githubusercontent.com/47611580/55967323-19b1e380-5c48-11e9-8ef7-452f01d38de6.png)

**Comment by ABonomo21** [comment]
same issue for townhouse test 240304

**Comment by ABonomo21** [comment]
Don- 
I retested there are a few minor issues to correct

City Impact A/P type-
RESTFD needs to generate the City Library Impact Fee - Attached
RESSFD- needs to generate the City School Impact Fee - Detached MS
RESMOB- needs to generate the City School Impact Fee - Detached MS
RESMTD- needs to generate the City Library Impact Fee - Other

**Comment by goggansd** [comment]
@megisys, unclear on City Library fee for SFD, as there are only two City Library fees:

![image](https://user-images.githubusercontent.com/28841997/55981086-0280ef00-5c64-11e9-9a6e-e2e8f4f71fd8.png)

The one with "SFD" in the description ALSO says it is for "ATTACHED", and the existing workflow indicates it is for Townhomes and Duplexes. The other one is currently coded as a catch-all for "other" scenarios, but those do not seem to be for an SFD scenario.

Fixed City School Impact Fee - Detached MS

**Comment by goggansd** [comment]
Fixed "RESTFD needs to generate the City Library Impact Fee"

**Comment by goggansd** [comment]
Fixed "RESMTD- needs to generate the City Library Impact Fee - Other"

**Comment by goggansd** [comment]
Fixed "RESMOB- needs to generate the City School Impact Fee - Detached MS"

**Comment by ABonomo21** [comment]
City Impact A/P type-
RESTFD needs to generate the City Library Impact Fee - Attached- CORRECTED 
RESSFD- needs to generate the City School Impact Fee - Detached MS- CORRECTED 
**RESMOB- needs to generate the City School Impact Fee - Detached MS- Needed fixed still missing 
RESMTD- needs to generate the City Library Impact Fee - Other**(should have been RESMFD I miss typed and put RESMTD.....

**Comment by goggansd** [comment]
Corrected RESMTD to be RESMFD.
Made RESMOB the same as RESSFD (correcting City Library Impact Fee - Detached MS)

**Comment by ABonomo21** [comment]
Thank you
