### ISSUE TITLE
Planning - Verification Letter - Finalized Application

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#74]
System appears to be out of syns - Application is "open" but also states "application has been finzalied on 2/19/2019. See screen shot below

Ap VP237212
Logged by A.Reed 

![image](https://user-images.githubusercontent.com/4129185/53107710-9d323c80-3503-11e9-937e-7d7195b92463.png)

**Comment by megisys** [comment]
Resolved - Adjusted Status Codes and Milestones

**Comment by dhenry-KCI** [comment]
![zoning verification letter - open - finalized](https://user-images.githubusercontent.com/4129185/53760123-f8631800-3e8f-11e9-9bd7-5907bc4c568c.PNG)
Planning - Verification Letter - Issue Not Resolved - 3/4/19 A/P# VP237468

**Comment by megisys** [comment]
Addressed this Issue

**Comment by dhenry-KCI** [comment]
Fixed - KVanaman - 3/5/19
![letter fix](https://user-images.githubusercontent.com/4129185/53835780-49d8d900-3f5c-11e9-8258-b84ccf643748.PNG)
